trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@1
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: ' $(agent.builddirectory)'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'